// HEXAGRAM PATTERN GENERATION METHODS
// coin_flip()
// Produces a hexagram pattern by simulating flipping three coins to
// produce a number from 6-9, six times in a row.

var coin_flip = () => {
  let hexagram_pattern = "";
  for(let i = 0; i < 6; i++) {
    hexagram_pattern += Math.floor(Math.random()*2) + Math.floor(Math.random()*2) + Math.floor(Math.random()*2) + 6;
  }
  return hexagram_pattern;
}

// HEXAGRAM IDENTIFICATION
// identify_hexagram()
// Takes a hexagram pattern and returns the hexagram from the BESTIARY
// that matches that pattern as an object.

var identify_hexagram = hexagram_pattern => BESTIARY.find(e => (e.pattern == hexagram_pattern));

// HEXAGRAM OBJECT
// this.raw = A raw hexagram pattern, generated by whatever method you please.
// this.primary - Converts raw hexagram pattern to valid primary hexagram pattern, then identifies.
// this.related - Converts raw hexagram pattern to valid related hexagram pattern, then identifies.

function Hexagram(method) {
  this.raw = method;
  this.primary = identify_hexagram(this.raw.replace(/6/g,"8").replace(/9/g,"7"));
  this.related = identify_hexagram(this.raw.replace(/6/g,"7").replace(/9/g,"8"));
}

// MAIN PROGRAM LOOP

// Create a new hexagram using the coin flip method
var myFortune = new Hexagram(coin_flip());

// Output symbol, name, judgment and image of primary hexagram info to
// #hexagram element using template strings.
document.querySelector("#hexagram").innerHTML = `
 <div class="symbol" lang="zh">${myFortune.primary.symbol}</div>
 <div class="identifier"><span lang="zh">${myFortune.primary.name.zh}</span> <i>${myFortune.primary.name.en}</i></div>
 <div class="judgment">${myFortune.primary.judgment}</div>
 <div class="image">${myFortune.primary.image}</div>
`;

// If primary and related hexagrams are not identical, output the
// lines that have changed to create the related hexagram.
if(myFortune.primary != myFortune.related) {
  document.querySelector("#hexagram div.symbol").innerHTML += myFortune.related.symbol; 
  document.querySelector("#hexagram div.identifier").innerHTML += `<br /><span lang="zh">${myFortune.related.name.zh}</span> <i>${myFortune.related.name.en}</i>`; 
  for(let i = 0; i < 6; i++) {
    if((myFortune.raw.charAt(i) % 3) == 0) {
      document.querySelector("#hexagram div.image").innerHTML += myFortune.primary.transforming_lines[i];
    }
  }

// In the unique case that all-yang changes to all-yin and vice-versa,
// output a special seventh transforming line.
  if ((myFortune.raw == "666666") || (myFortune.raw == "999999")) {
    document.querySelector("#hexagram div.image").innerHTML += myFortune.primary.transforming_lines[6];
  }

// Output image of related hexagram.
  document.querySelector("#hexagram div.image").innerHTML += myFortune.related.image;
}
